# Page settings

baseURL = ""
languageCode = "en"
title = "Ishank Mishra"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Ishank"
    description = "Ishank Mishra Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ishank Mishra"
        tagline = "Software Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Los Angeles, California"

        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.ishankmishra.me"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Programming"
        [[params.skills.list.items]]
        details = "C# ![Progress](assets/images/adv.png)"
        [[params.skills.list.items]]
        details = "Python ![Progress](assets/images/adv.png)"
        [[params.skills.list.items]]
        details = "Java ![Progress](assets/images/prof.png)"
        [[params.skills.list.items]]
        details = "JavaScript ![Progress](assets/images/prof.png)"
        [[params.skills.list.items]]
        details = "Scala ![Progress](assets/images/int.png)"
        [[params.skills.list.items]]
        details = "C++ ![Progress](assets/images/prof.png)"
        [[params.skills.list.items]]
        details = "Familiar: C, Go, Matlab, ABAP"

        [[params.skills.list]]
        title = "Development"
        [[params.skills.list.items]]
        details = "Microservices"
        [[params.skills.list.items]]
        details = "Dependency Injection"
        [[params.skills.list.items]]
        details = "MVC"
        [[params.skills.list.items]]
        details = "TDD, Containers, CI/CD, SQL, Git"

        [[params.skills.list]]
        title = "Frameworks"
        [[params.skills.list.items]]
        details = ".NET"
        [[params.skills.list.items]]
        details = "React, Redux, AngularJS"
        [[params.skills.list.items]]
        details = "NodeJS, Flask"
        [[params.skills.list.items]]
        details = "HANA, Fiori"

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "AWS, Jenkins, Terraform"
        [[params.skills.list.items]]
        details = "Redis, Kafka, RabbitMQ"
        [[params.skills.list.items]]
        details = "Microsoft SQL Server, MongoDb, Firebase, DynamoDb, PostgreSQL"
        [[params.skills.list.items]]
        details = "ELK, Splunk"

        [[params.skills.list]]
        title = "Data Science"
        [[params.skills.list.items]]
        details = "Spark, TensorFlow, Keras, Scikit-Learn"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MS in Computer Science"
        university = "University of Southern California"
        dates = "2017 - 2019"
        [[params.education.list]]
        degree = "BE Information Science and Engineering"
        university = "MS Ramaiah Institute of Technology"
        dates = "2010 - 2014"









    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Hindi"
        level = "Native"
        [[params.languages.list]]
        name = "German"
        level = "Beginner"
        [[params.languages.list]]
        name = "Hindi"
        level = "Beginner"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Painting"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Software Developer with a strong background in object oriented principles and design. Believer in pragmatic solutions, maintainable and scalable design. Backend Engineer with proficiency in common design patterns such as Microservices, Dependency Injection, MVC, TDD, etc. Computer Science graduate and USC Alumni with over 4 years of experience working as a software developer for leading organizations such as Ellie Mae, SAP Labs, and Cognizant. "








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "Jun 2019 - Present"
        company = "Ellie Mae"
        details = "Velocify Core Platform Infrastructure | Backend development"
        [[params.experience.list.items]]
        details = "Designed and developed several scalable, performant, and resilient RESTful APIs using Microservices architecture hosted on AWS cloud infrastructure."
        [[params.experience.list.items]]
        details = "Developed several features and improvements to an MVC based web application using C# and .NET Framework."
        [[params.experience.list.items]]
        details = "Improved and aided in creation of several libraries which are being used across various development teams."
        [[params.experience.list.items]]
        details = "Built the CI/CD pipelines for Microservices running on Docker containers using Jenkins and Terraform."
        [[params.experience.list.items]]
        details = "Improved code quality and testability by implementing automated testing in applications and services using best practices and coding standards."
        [[params.experience.list.items]]
        details = "Technologies: C#, .Net, Microsoft SQL server, Microservices, Redis, Kafka, RabbitMQ, Docker, Jenkins, Terraform, AWS."
        
        [[params.experience.list]]
        title = "Software Developer Intern"
        dates = "Jun 2018 - Aug 2018"
        company = "Ellie Mae"
        details = "Designed and developed a feature-package management module, a part of core infrastructure platform’s admin tool, that enables product administrators to schedule feature-package management tasks. Technologies: AngularJS, C#, .Net, MS SQL Server, TFS."

        [[params.experience.list]]
        title = "Developer Associate"
        dates = "Mar 2015 - Jul 2017"
        company = "SAP"
        details = "S/4 HANA Product Master | Backend development"
        [[params.experience.list.items]]
        details = "Designed and developed the RESTful Services for the S/4 HANA Product Master Application using ABAP, HANA database, and the NetWeaver platform deployed on SAP Cloud Platform."
        [[params.experience.list.items]]
        details = "Built the draft enablement functionality for Product Master Application using the HANA platform. The functionality enabled users to save intermediate states of Material Master data as drafts with seamless search capability alongside active data."
        [[params.experience.list.items]]
        details = "Integrated the ERP Master Data with Supply Chain Management and Retail Master Data. The integration enabled users to access data from three domains i.e. ERP, SCM, and Retail, using the Product Maser Application."
        [[params.experience.list.items]]
        details = "Led a development team of 5 to design and build a Dashboard application that provided analytics based on historical data about state of plants and storage locations in S/4 HANA. The application was showcased as part of Innovation projects in S/4 HANA domain. Received the Rising Star award for the project in Dec 2016."
        [[params.experience.list.items]]
        details = "Technologies: ABAP (Object oriented programming), HANA, Fiori (JavaScript)"

        [[params.experience.list]]
        title = "Programmer Analyst Trainee"
        dates = "Sep 2014 - Feb 2015"
        company = "Cognizant"
        details = "Full Stack Development | .Net Framework"
        [[params.experience.list.items]]
        details = "Designed and developed an MVC based web application for an online book store as part of an internal project. Technologies: C#, ASP.NET, Microsoft SQL Server"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Deep Link Prediction for Graphical Database"
        meta = "Jan 2019 – May 2019"
        tagline = "Devised a method to predict bankruptcies of companies using a Graph Convolutional Neural Network. The approach used was to solve the multi-relational link prediction task in a multi modal finance graph stored in a graphical database. Technologies used: Tensorflow, Neo4j. Built a Java plugin for Neo4j to query the database using an Approximate Nearest Neighbors algorithm called annoy."

        [[params.projects.list]]
        title = "Movie Recommendation System using Collaborative filtering and Alternating Least Squares"
        meta = "Jul 2018 – Aug 2018"
        tagline = "Implemented several recommendation systems using the MovieLens dataset. The techniques applied are user-based and item-based collaborative filtering, alternating least squares algorithm. Technologies: Spark, Scala"

        [[params.projects.list]]
        title = "Twitter data sampling application using reservoir sampling"
        meta = "Jul 2018"
        tagline = "Designed and developed a real-time web application to sample data from a continuous stream of tweets using reservoir sampling method. The application also provides statistics based on the sampled data. Technologies used: Python (Flask, Socket.io), React, Redux"
        
        [[params.projects.list]]
        title = "Automated customer feedback service using sentiment analysis of text messages"
        meta = "Feb 2018"
        tagline = "Designed and built an interactive web application to collect customer feedback using text messages. The application interacted with customers based on the sentiment analysis of their replies. Technologies used: Python Flask, MongoDB, Bootstrap, RESTful Apis, Microsoft Azure, Twilio."
        
        [[params.projects.list]]
        title = "Survey Application"
        meta = "Jan 2018"
        tagline = "Designed and developed a web/android application to conduct online surveys. Technologies used: Ionic, AngularJS, Firebase"
        
        [[params.projects.list]]
        title = "N plus K Queens problem using simulated annealing"
        meta = "Nov 2017"
        tagline = "Devised an approach to solve the N plus K Queens problem using simulated annealing. Built an interactive web application to demonstrate the approach in various settings"
        
        [[params.projects.list]]
        title = "Game playing AI agent"
        meta = "Oct 2017"
        tagline = "Built a game playing AI agent for game called fruit rage (description in repo). The AI agent used the minimax algorithm to maximize it's chances of winning. Built an interactive UI game that allowed players to play against the AI agent using the TKinter library in Python."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2015 · Phylogenetic analysis Using MapReduce Programming Model . IEEE International Parallel and Distributed Computing Symposium"









    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/ishankkm"
        title = "ishankkm"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/ishankmishra/"
        title = "ishankmishra"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/ishankmishra"
        title = "@ishankmishra"





